//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.ProductoXZonaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="ProductoXZonaWS.ProductoXZonaWS")]
    public interface ProductoXZonaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/listarProductosXZonasRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/listarProductosXZonasRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse listarProductosXZonas(CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/listarProductosXZonasRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/listarProductosXZonasRe" +
            "sponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse> listarProductosXZonasAsync(CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/insertarProductoXZonaRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/insertarProductoXZonaRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse insertarProductoXZona(CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/insertarProductoXZonaRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoXZonaWS/insertarProductoXZonaRe" +
            "sponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse> insertarProductoXZonaAsync(CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class productoXZona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idProductoXZonaField;
        
        private double precioRealField;
        
        private producto productoField;
        
        private zona zonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProductoXZona {
            get {
                return this.idProductoXZonaField;
            }
            set {
                this.idProductoXZonaField = value;
                this.RaisePropertyChanged("idProductoXZona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioReal {
            get {
                return this.precioRealField;
            }
            set {
                this.precioRealField = value;
                this.RaisePropertyChanged("precioReal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public zona zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private double cantUnidadField;
        
        private int idProductoField;
        
        private marca marcaField;
        
        private string nombreField;
        
        private double precioSugeridoField;
        
        private int stockField;
        
        private int stockReservadoField;
        
        private subFamilia subFamiliaField;
        
        private string unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cantUnidad {
            get {
                return this.cantUnidadField;
            }
            set {
                this.cantUnidadField = value;
                this.RaisePropertyChanged("cantUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public marca marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioSugerido {
            get {
                return this.precioSugeridoField;
            }
            set {
                this.precioSugeridoField = value;
                this.RaisePropertyChanged("precioSugerido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockReservado {
            get {
                return this.stockReservadoField;
            }
            set {
                this.stockReservadoField = value;
                this.RaisePropertyChanged("stockReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public subFamilia subFamilia {
            get {
                return this.subFamiliaField;
            }
            set {
                this.subFamiliaField = value;
                this.RaisePropertyChanged("subFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idMarcaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                this.idMarcaField = value;
                this.RaisePropertyChanged("idMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class zona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idZonaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idZona {
            get {
                return this.idZonaField;
            }
            set {
                this.idZonaField = value;
                this.RaisePropertyChanged("idZona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class familia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idFamiliaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                this.idFamiliaField = value;
                this.RaisePropertyChanged("idFamilia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class subFamilia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionSubFamiliaField;
        
        private familia familiaField;
        
        private int idSubFamiliaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionSubFamilia {
            get {
                return this.descripcionSubFamiliaField;
            }
            set {
                this.descripcionSubFamiliaField = value;
                this.RaisePropertyChanged("descripcionSubFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public familia familia {
            get {
                return this.familiaField;
            }
            set {
                this.familiaField = value;
                this.RaisePropertyChanged("familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idSubFamilia {
            get {
                return this.idSubFamiliaField;
            }
            set {
                this.idSubFamiliaField = value;
                this.RaisePropertyChanged("idSubFamilia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosXZonas", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosXZonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productoStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zonaStr;
        
        public listarProductosXZonasRequest() {
        }
        
        public listarProductosXZonasRequest(string productoStr, string zonaStr) {
            this.productoStr = productoStr;
            this.zonaStr = zonaStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosXZonasResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosXZonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoXZonaWS.productoXZona[] @return;
        
        public listarProductosXZonasResponse() {
        }
        
        public listarProductosXZonasResponse(CrewmanSystem.ProductoXZonaWS.productoXZona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoXZona", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoXZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoXZonaWS.productoXZona productoXZona;
        
        public insertarProductoXZonaRequest() {
        }
        
        public insertarProductoXZonaRequest(CrewmanSystem.ProductoXZonaWS.productoXZona productoXZona) {
            this.productoXZona = productoXZona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoXZonaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoXZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoXZonaResponse() {
        }
        
        public insertarProductoXZonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoXZonaWSChannel : CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoXZonaWSClient : System.ServiceModel.ClientBase<CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS>, CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS {
        
        public ProductoXZonaWSClient() {
        }
        
        public ProductoXZonaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoXZonaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoXZonaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoXZonaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS.listarProductosXZonas(CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest request) {
            return base.Channel.listarProductosXZonas(request);
        }
        
        public CrewmanSystem.ProductoXZonaWS.productoXZona[] listarProductosXZonas(string productoStr, string zonaStr) {
            CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest inValue = new CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest();
            inValue.productoStr = productoStr;
            inValue.zonaStr = zonaStr;
            CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse retVal = ((CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS)(this)).listarProductosXZonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse> CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS.listarProductosXZonasAsync(CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest request) {
            return base.Channel.listarProductosXZonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.listarProductosXZonasResponse> listarProductosXZonasAsync(string productoStr, string zonaStr) {
            CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest inValue = new CrewmanSystem.ProductoXZonaWS.listarProductosXZonasRequest();
            inValue.productoStr = productoStr;
            inValue.zonaStr = zonaStr;
            return ((CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS)(this)).listarProductosXZonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS.insertarProductoXZona(CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest request) {
            return base.Channel.insertarProductoXZona(request);
        }
        
        public int insertarProductoXZona(CrewmanSystem.ProductoXZonaWS.productoXZona productoXZona) {
            CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest inValue = new CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest();
            inValue.productoXZona = productoXZona;
            CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse retVal = ((CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS)(this)).insertarProductoXZona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse> CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS.insertarProductoXZonaAsync(CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest request) {
            return base.Channel.insertarProductoXZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaResponse> insertarProductoXZonaAsync(CrewmanSystem.ProductoXZonaWS.productoXZona productoXZona) {
            CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest inValue = new CrewmanSystem.ProductoXZonaWS.insertarProductoXZonaRequest();
            inValue.productoXZona = productoXZona;
            return ((CrewmanSystem.ProductoXZonaWS.ProductoXZonaWS)(this)).insertarProductoXZonaAsync(inValue);
        }
    }
}
