//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.MarcaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="MarcaWS.MarcaWS")]
    public interface MarcaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/insertarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/insertarMarcaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.MarcaWS.insertarMarcaResponse insertarMarca(CrewmanSystem.MarcaWS.insertarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/insertarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/insertarMarcaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.insertarMarcaResponse> insertarMarcaAsync(CrewmanSystem.MarcaWS.insertarMarcaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/eliminarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/eliminarMarcaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.MarcaWS.eliminarMarcaResponse eliminarMarca(CrewmanSystem.MarcaWS.eliminarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/eliminarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/eliminarMarcaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.eliminarMarcaResponse> eliminarMarcaAsync(CrewmanSystem.MarcaWS.eliminarMarcaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/listarMarcasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/listarMarcasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.MarcaWS.listarMarcasResponse listarMarcas(CrewmanSystem.MarcaWS.listarMarcasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/listarMarcasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/listarMarcasResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.listarMarcasResponse> listarMarcasAsync(CrewmanSystem.MarcaWS.listarMarcasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/actualizarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/actualizarMarcaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.MarcaWS.actualizarMarcaResponse actualizarMarca(CrewmanSystem.MarcaWS.actualizarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/actualizarMarcaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/MarcaWS/actualizarMarcaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.actualizarMarcaResponse> actualizarMarcaAsync(CrewmanSystem.MarcaWS.actualizarMarcaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idMarcaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                this.idMarcaField = value;
                this.RaisePropertyChanged("idMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMarca", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.MarcaWS.marca marca;
        
        public insertarMarcaRequest() {
        }
        
        public insertarMarcaRequest(CrewmanSystem.MarcaWS.marca marca) {
            this.marca = marca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMarcaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMarcaResponse() {
        }
        
        public insertarMarcaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMarca", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMarca;
        
        public eliminarMarcaRequest() {
        }
        
        public eliminarMarcaRequest(int idMarca) {
            this.idMarca = idMarca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMarcaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMarcaResponse() {
        }
        
        public eliminarMarcaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMarcas", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMarcasRequest {
        
        public listarMarcasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMarcasResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMarcasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.MarcaWS.marca[] @return;
        
        public listarMarcasResponse() {
        }
        
        public listarMarcasResponse(CrewmanSystem.MarcaWS.marca[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMarca", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.MarcaWS.marca marca;
        
        public actualizarMarcaRequest() {
        }
        
        public actualizarMarcaRequest(CrewmanSystem.MarcaWS.marca marca) {
            this.marca = marca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarMarcaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarMarcaResponse() {
        }
        
        public actualizarMarcaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MarcaWSChannel : CrewmanSystem.MarcaWS.MarcaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarcaWSClient : System.ServiceModel.ClientBase<CrewmanSystem.MarcaWS.MarcaWS>, CrewmanSystem.MarcaWS.MarcaWS {
        
        public MarcaWSClient() {
        }
        
        public MarcaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarcaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarcaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.MarcaWS.insertarMarcaResponse CrewmanSystem.MarcaWS.MarcaWS.insertarMarca(CrewmanSystem.MarcaWS.insertarMarcaRequest request) {
            return base.Channel.insertarMarca(request);
        }
        
        public int insertarMarca(CrewmanSystem.MarcaWS.marca marca) {
            CrewmanSystem.MarcaWS.insertarMarcaRequest inValue = new CrewmanSystem.MarcaWS.insertarMarcaRequest();
            inValue.marca = marca;
            CrewmanSystem.MarcaWS.insertarMarcaResponse retVal = ((CrewmanSystem.MarcaWS.MarcaWS)(this)).insertarMarca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.insertarMarcaResponse> CrewmanSystem.MarcaWS.MarcaWS.insertarMarcaAsync(CrewmanSystem.MarcaWS.insertarMarcaRequest request) {
            return base.Channel.insertarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.insertarMarcaResponse> insertarMarcaAsync(CrewmanSystem.MarcaWS.marca marca) {
            CrewmanSystem.MarcaWS.insertarMarcaRequest inValue = new CrewmanSystem.MarcaWS.insertarMarcaRequest();
            inValue.marca = marca;
            return ((CrewmanSystem.MarcaWS.MarcaWS)(this)).insertarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.MarcaWS.eliminarMarcaResponse CrewmanSystem.MarcaWS.MarcaWS.eliminarMarca(CrewmanSystem.MarcaWS.eliminarMarcaRequest request) {
            return base.Channel.eliminarMarca(request);
        }
        
        public int eliminarMarca(int idMarca) {
            CrewmanSystem.MarcaWS.eliminarMarcaRequest inValue = new CrewmanSystem.MarcaWS.eliminarMarcaRequest();
            inValue.idMarca = idMarca;
            CrewmanSystem.MarcaWS.eliminarMarcaResponse retVal = ((CrewmanSystem.MarcaWS.MarcaWS)(this)).eliminarMarca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.eliminarMarcaResponse> CrewmanSystem.MarcaWS.MarcaWS.eliminarMarcaAsync(CrewmanSystem.MarcaWS.eliminarMarcaRequest request) {
            return base.Channel.eliminarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.eliminarMarcaResponse> eliminarMarcaAsync(int idMarca) {
            CrewmanSystem.MarcaWS.eliminarMarcaRequest inValue = new CrewmanSystem.MarcaWS.eliminarMarcaRequest();
            inValue.idMarca = idMarca;
            return ((CrewmanSystem.MarcaWS.MarcaWS)(this)).eliminarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.MarcaWS.listarMarcasResponse CrewmanSystem.MarcaWS.MarcaWS.listarMarcas(CrewmanSystem.MarcaWS.listarMarcasRequest request) {
            return base.Channel.listarMarcas(request);
        }
        
        public CrewmanSystem.MarcaWS.marca[] listarMarcas() {
            CrewmanSystem.MarcaWS.listarMarcasRequest inValue = new CrewmanSystem.MarcaWS.listarMarcasRequest();
            CrewmanSystem.MarcaWS.listarMarcasResponse retVal = ((CrewmanSystem.MarcaWS.MarcaWS)(this)).listarMarcas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.listarMarcasResponse> CrewmanSystem.MarcaWS.MarcaWS.listarMarcasAsync(CrewmanSystem.MarcaWS.listarMarcasRequest request) {
            return base.Channel.listarMarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.listarMarcasResponse> listarMarcasAsync() {
            CrewmanSystem.MarcaWS.listarMarcasRequest inValue = new CrewmanSystem.MarcaWS.listarMarcasRequest();
            return ((CrewmanSystem.MarcaWS.MarcaWS)(this)).listarMarcasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.MarcaWS.actualizarMarcaResponse CrewmanSystem.MarcaWS.MarcaWS.actualizarMarca(CrewmanSystem.MarcaWS.actualizarMarcaRequest request) {
            return base.Channel.actualizarMarca(request);
        }
        
        public int actualizarMarca(CrewmanSystem.MarcaWS.marca marca) {
            CrewmanSystem.MarcaWS.actualizarMarcaRequest inValue = new CrewmanSystem.MarcaWS.actualizarMarcaRequest();
            inValue.marca = marca;
            CrewmanSystem.MarcaWS.actualizarMarcaResponse retVal = ((CrewmanSystem.MarcaWS.MarcaWS)(this)).actualizarMarca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.actualizarMarcaResponse> CrewmanSystem.MarcaWS.MarcaWS.actualizarMarcaAsync(CrewmanSystem.MarcaWS.actualizarMarcaRequest request) {
            return base.Channel.actualizarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.MarcaWS.actualizarMarcaResponse> actualizarMarcaAsync(CrewmanSystem.MarcaWS.marca marca) {
            CrewmanSystem.MarcaWS.actualizarMarcaRequest inValue = new CrewmanSystem.MarcaWS.actualizarMarcaRequest();
            inValue.marca = marca;
            return ((CrewmanSystem.MarcaWS.MarcaWS)(this)).actualizarMarcaAsync(inValue);
        }
    }
}
