//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.ProductoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="ProductoWS.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/mostrarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/mostrarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoWS.mostrarProductoResponse mostrarProducto(CrewmanSystem.ProductoWS.mostrarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/mostrarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/mostrarProductoResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.mostrarProductoResponse> mostrarProductoAsync(CrewmanSystem.ProductoWS.mostrarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/listarProductosRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/listarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoWS.listarProductosResponse listarProductos(CrewmanSystem.ProductoWS.listarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/listarProductosRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/listarProductosResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.listarProductosResponse> listarProductosAsync(CrewmanSystem.ProductoWS.listarProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/insertarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoWS.insertarProductoResponse insertarProducto(CrewmanSystem.ProductoWS.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/insertarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/insertarProductoResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.insertarProductoResponse> insertarProductoAsync(CrewmanSystem.ProductoWS.insertarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/eliminarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoWS.eliminarProductoResponse eliminarProducto(CrewmanSystem.ProductoWS.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/eliminarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/eliminarProductoResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.eliminarProductoResponse> eliminarProductoAsync(CrewmanSystem.ProductoWS.eliminarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/actualizarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/actualizarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ProductoWS.actualizarProductoResponse actualizarProducto(CrewmanSystem.ProductoWS.actualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/actualizarProductoRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ProductoWS/actualizarProductoResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.actualizarProductoResponse> actualizarProductoAsync(CrewmanSystem.ProductoWS.actualizarProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private double cantUnidadField;
        
        private int idProductoField;
        
        private marca marcaField;
        
        private string nombreField;
        
        private double precioSugeridoField;
        
        private int stockField;
        
        private int stockReservadoField;
        
        private subFamilia subFamiliaField;
        
        private string unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cantUnidad {
            get {
                return this.cantUnidadField;
            }
            set {
                this.cantUnidadField = value;
                this.RaisePropertyChanged("cantUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public marca marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioSugerido {
            get {
                return this.precioSugeridoField;
            }
            set {
                this.precioSugeridoField = value;
                this.RaisePropertyChanged("precioSugerido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockReservado {
            get {
                return this.stockReservadoField;
            }
            set {
                this.stockReservadoField = value;
                this.RaisePropertyChanged("stockReservado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public subFamilia subFamilia {
            get {
                return this.subFamiliaField;
            }
            set {
                this.subFamiliaField = value;
                this.RaisePropertyChanged("subFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class marca : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idMarcaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMarca {
            get {
                return this.idMarcaField;
            }
            set {
                this.idMarcaField = value;
                this.RaisePropertyChanged("idMarca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class familia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idFamiliaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                this.idFamiliaField = value;
                this.RaisePropertyChanged("idFamilia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class subFamilia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionSubFamiliaField;
        
        private familia familiaField;
        
        private int idSubFamiliaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionSubFamilia {
            get {
                return this.descripcionSubFamiliaField;
            }
            set {
                this.descripcionSubFamiliaField = value;
                this.RaisePropertyChanged("descripcionSubFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public familia familia {
            get {
                return this.familiaField;
            }
            set {
                this.familiaField = value;
                this.RaisePropertyChanged("familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idSubFamilia {
            get {
                return this.idSubFamiliaField;
            }
            set {
                this.idSubFamiliaField = value;
                this.RaisePropertyChanged("idSubFamilia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarProducto", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public mostrarProductoRequest() {
        }
        
        public mostrarProductoRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarProductoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoWS.producto @return;
        
        public mostrarProductoResponse() {
        }
        
        public mostrarProductoResponse(CrewmanSystem.ProductoWS.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductos", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string familiaStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subFamiliaStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marcaStr;
        
        public listarProductosRequest() {
        }
        
        public listarProductosRequest(string nombre, string familiaStr, string subFamiliaStr, string marcaStr) {
            this.nombre = nombre;
            this.familiaStr = familiaStr;
            this.subFamiliaStr = subFamiliaStr;
            this.marcaStr = marcaStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoWS.producto[] @return;
        
        public listarProductosResponse() {
        }
        
        public listarProductosResponse(CrewmanSystem.ProductoWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoWS.producto producto;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(CrewmanSystem.ProductoWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoResponse() {
        }
        
        public insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoResponse() {
        }
        
        public eliminarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProducto", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.ProductoWS.producto producto;
        
        public actualizarProductoRequest() {
        }
        
        public actualizarProductoRequest(CrewmanSystem.ProductoWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProductoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarProductoResponse() {
        }
        
        public actualizarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : CrewmanSystem.ProductoWS.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<CrewmanSystem.ProductoWS.ProductoWS>, CrewmanSystem.ProductoWS.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoWS.mostrarProductoResponse CrewmanSystem.ProductoWS.ProductoWS.mostrarProducto(CrewmanSystem.ProductoWS.mostrarProductoRequest request) {
            return base.Channel.mostrarProducto(request);
        }
        
        public CrewmanSystem.ProductoWS.producto mostrarProducto(int idProducto) {
            CrewmanSystem.ProductoWS.mostrarProductoRequest inValue = new CrewmanSystem.ProductoWS.mostrarProductoRequest();
            inValue.idProducto = idProducto;
            CrewmanSystem.ProductoWS.mostrarProductoResponse retVal = ((CrewmanSystem.ProductoWS.ProductoWS)(this)).mostrarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.mostrarProductoResponse> CrewmanSystem.ProductoWS.ProductoWS.mostrarProductoAsync(CrewmanSystem.ProductoWS.mostrarProductoRequest request) {
            return base.Channel.mostrarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.mostrarProductoResponse> mostrarProductoAsync(int idProducto) {
            CrewmanSystem.ProductoWS.mostrarProductoRequest inValue = new CrewmanSystem.ProductoWS.mostrarProductoRequest();
            inValue.idProducto = idProducto;
            return ((CrewmanSystem.ProductoWS.ProductoWS)(this)).mostrarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoWS.listarProductosResponse CrewmanSystem.ProductoWS.ProductoWS.listarProductos(CrewmanSystem.ProductoWS.listarProductosRequest request) {
            return base.Channel.listarProductos(request);
        }
        
        public CrewmanSystem.ProductoWS.producto[] listarProductos(string nombre, string familiaStr, string subFamiliaStr, string marcaStr) {
            CrewmanSystem.ProductoWS.listarProductosRequest inValue = new CrewmanSystem.ProductoWS.listarProductosRequest();
            inValue.nombre = nombre;
            inValue.familiaStr = familiaStr;
            inValue.subFamiliaStr = subFamiliaStr;
            inValue.marcaStr = marcaStr;
            CrewmanSystem.ProductoWS.listarProductosResponse retVal = ((CrewmanSystem.ProductoWS.ProductoWS)(this)).listarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.listarProductosResponse> CrewmanSystem.ProductoWS.ProductoWS.listarProductosAsync(CrewmanSystem.ProductoWS.listarProductosRequest request) {
            return base.Channel.listarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.listarProductosResponse> listarProductosAsync(string nombre, string familiaStr, string subFamiliaStr, string marcaStr) {
            CrewmanSystem.ProductoWS.listarProductosRequest inValue = new CrewmanSystem.ProductoWS.listarProductosRequest();
            inValue.nombre = nombre;
            inValue.familiaStr = familiaStr;
            inValue.subFamiliaStr = subFamiliaStr;
            inValue.marcaStr = marcaStr;
            return ((CrewmanSystem.ProductoWS.ProductoWS)(this)).listarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoWS.insertarProductoResponse CrewmanSystem.ProductoWS.ProductoWS.insertarProducto(CrewmanSystem.ProductoWS.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public int insertarProducto(CrewmanSystem.ProductoWS.producto producto) {
            CrewmanSystem.ProductoWS.insertarProductoRequest inValue = new CrewmanSystem.ProductoWS.insertarProductoRequest();
            inValue.producto = producto;
            CrewmanSystem.ProductoWS.insertarProductoResponse retVal = ((CrewmanSystem.ProductoWS.ProductoWS)(this)).insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.insertarProductoResponse> CrewmanSystem.ProductoWS.ProductoWS.insertarProductoAsync(CrewmanSystem.ProductoWS.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.insertarProductoResponse> insertarProductoAsync(CrewmanSystem.ProductoWS.producto producto) {
            CrewmanSystem.ProductoWS.insertarProductoRequest inValue = new CrewmanSystem.ProductoWS.insertarProductoRequest();
            inValue.producto = producto;
            return ((CrewmanSystem.ProductoWS.ProductoWS)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoWS.eliminarProductoResponse CrewmanSystem.ProductoWS.ProductoWS.eliminarProducto(CrewmanSystem.ProductoWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public int eliminarProducto(int idProducto) {
            CrewmanSystem.ProductoWS.eliminarProductoRequest inValue = new CrewmanSystem.ProductoWS.eliminarProductoRequest();
            inValue.idProducto = idProducto;
            CrewmanSystem.ProductoWS.eliminarProductoResponse retVal = ((CrewmanSystem.ProductoWS.ProductoWS)(this)).eliminarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.eliminarProductoResponse> CrewmanSystem.ProductoWS.ProductoWS.eliminarProductoAsync(CrewmanSystem.ProductoWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.eliminarProductoResponse> eliminarProductoAsync(int idProducto) {
            CrewmanSystem.ProductoWS.eliminarProductoRequest inValue = new CrewmanSystem.ProductoWS.eliminarProductoRequest();
            inValue.idProducto = idProducto;
            return ((CrewmanSystem.ProductoWS.ProductoWS)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ProductoWS.actualizarProductoResponse CrewmanSystem.ProductoWS.ProductoWS.actualizarProducto(CrewmanSystem.ProductoWS.actualizarProductoRequest request) {
            return base.Channel.actualizarProducto(request);
        }
        
        public int actualizarProducto(CrewmanSystem.ProductoWS.producto producto) {
            CrewmanSystem.ProductoWS.actualizarProductoRequest inValue = new CrewmanSystem.ProductoWS.actualizarProductoRequest();
            inValue.producto = producto;
            CrewmanSystem.ProductoWS.actualizarProductoResponse retVal = ((CrewmanSystem.ProductoWS.ProductoWS)(this)).actualizarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.actualizarProductoResponse> CrewmanSystem.ProductoWS.ProductoWS.actualizarProductoAsync(CrewmanSystem.ProductoWS.actualizarProductoRequest request) {
            return base.Channel.actualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ProductoWS.actualizarProductoResponse> actualizarProductoAsync(CrewmanSystem.ProductoWS.producto producto) {
            CrewmanSystem.ProductoWS.actualizarProductoRequest inValue = new CrewmanSystem.ProductoWS.actualizarProductoRequest();
            inValue.producto = producto;
            return ((CrewmanSystem.ProductoWS.ProductoWS)(this)).actualizarProductoAsync(inValue);
        }
    }
}
