//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.LineaCreditoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="LineaCreditoWS.LineaCreditoWS")]
    public interface LineaCreditoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/insertarLineaCreditoRequ" +
            "est", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/insertarLineaCreditoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse insertarLineaCredito(CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/insertarLineaCreditoRequ" +
            "est", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/insertarLineaCreditoResp" +
            "onse")]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse> insertarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/actualizarLineaCreditoRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/actualizarLineaCreditoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse actualizarLineaCredito(CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/actualizarLineaCreditoRe" +
            "quest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/actualizarLineaCreditoRe" +
            "sponse")]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse> actualizarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/mostrarLineaCreditosRequ" +
            "est", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/mostrarLineaCreditosResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse mostrarLineaCreditos(CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/mostrarLineaCreditosRequ" +
            "est", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/LineaCreditoWS/mostrarLineaCreditosResp" +
            "onse")]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse> mostrarLineaCreditosAsync(CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class lineaCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool aprobadoField;
        
        private cliente clienteField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idLineaCreditoField;
        
        private double montoLineaCreditoField;
        
        private double montoUtilizadoField;
        
        private string motivoField;
        
        private empleado responsableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool aprobado {
            get {
                return this.aprobadoField;
            }
            set {
                this.aprobadoField = value;
                this.RaisePropertyChanged("aprobado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idLineaCredito {
            get {
                return this.idLineaCreditoField;
            }
            set {
                this.idLineaCreditoField = value;
                this.RaisePropertyChanged("idLineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double montoLineaCredito {
            get {
                return this.montoLineaCreditoField;
            }
            set {
                this.montoLineaCreditoField = value;
                this.RaisePropertyChanged("montoLineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double montoUtilizado {
            get {
                return this.montoUtilizadoField;
            }
            set {
                this.montoUtilizadoField = value;
                this.RaisePropertyChanged("montoUtilizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public empleado responsable {
            get {
                return this.responsableField;
            }
            set {
                this.responsableField = value;
                this.RaisePropertyChanged("responsable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private cartera carteraField;
        
        private string direccionField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private System.DateTime fechaUltimaCompraField;
        
        private bool fechaUltimaCompraFieldSpecified;
        
        private string grupoField;
        
        private int idClienteField;
        
        private lineaCredito lineaCreditoField;
        
        private personaContacto personaContactoField;
        
        private string razonSocialField;
        
        private string rucField;
        
        private string tipoEmpresaField;
        
        private zona zonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cartera cartera {
            get {
                return this.carteraField;
            }
            set {
                this.carteraField = value;
                this.RaisePropertyChanged("cartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaUltimaCompra {
            get {
                return this.fechaUltimaCompraField;
            }
            set {
                this.fechaUltimaCompraField = value;
                this.RaisePropertyChanged("fechaUltimaCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaUltimaCompraSpecified {
            get {
                return this.fechaUltimaCompraFieldSpecified;
            }
            set {
                this.fechaUltimaCompraFieldSpecified = value;
                this.RaisePropertyChanged("fechaUltimaCompraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string grupo {
            get {
                return this.grupoField;
            }
            set {
                this.grupoField = value;
                this.RaisePropertyChanged("grupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public lineaCredito lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public personaContacto personaContacto {
            get {
                return this.personaContactoField;
            }
            set {
                this.personaContactoField = value;
                this.RaisePropertyChanged("personaContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tipoEmpresa {
            get {
                return this.tipoEmpresaField;
            }
            set {
                this.tipoEmpresaField = value;
                this.RaisePropertyChanged("tipoEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public zona zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class cartera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private visita[] listaVisitaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaVisita", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public visita[] listaVisita {
            get {
                return this.listaVisitaField;
            }
            set {
                this.listaVisitaField = value;
                this.RaisePropertyChanged("listaVisita");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class empleado : persona {
        
        private cargo cargoField;
        
        private cartera carteraField;
        
        private string contraseñaField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idEmpleadoField;
        
        private empleado jefeField;
        
        private double objetivoVentasField;
        
        private double sumVentasField;
        
        private string usuarioField;
        
        private zona zonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cargo cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cartera cartera {
            get {
                return this.carteraField;
            }
            set {
                this.carteraField = value;
                this.RaisePropertyChanged("cartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                this.idEmpleadoField = value;
                this.RaisePropertyChanged("idEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public empleado jefe {
            get {
                return this.jefeField;
            }
            set {
                this.jefeField = value;
                this.RaisePropertyChanged("jefe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double objetivoVentas {
            get {
                return this.objetivoVentasField;
            }
            set {
                this.objetivoVentasField = value;
                this.RaisePropertyChanged("objetivoVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double sumVentas {
            get {
                return this.sumVentasField;
            }
            set {
                this.sumVentasField = value;
                this.RaisePropertyChanged("sumVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public zona zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idCargoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
                this.RaisePropertyChanged("idCargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class visita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private cartera carteraField;
        
        private cliente clienteField;
        
        private empleado empleadoField;
        
        private bool estadoField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idVisitaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cartera cartera {
            get {
                return this.carteraField;
            }
            set {
                this.carteraField = value;
                this.RaisePropertyChanged("cartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idVisita {
            get {
                return this.idVisitaField;
            }
            set {
                this.idVisitaField = value;
                this.RaisePropertyChanged("idVisita");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class zona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idZonaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idZona {
            get {
                return this.idZonaField;
            }
            set {
                this.idZonaField = value;
                this.RaisePropertyChanged("idZona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personaContacto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoField;
        
        private string dniField;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private persona persona1Field;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public persona persona1 {
            get {
                return this.persona1Field;
            }
            set {
                this.persona1Field = value;
                this.RaisePropertyChanged("persona1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
                this.RaisePropertyChanged("telefono1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
                this.RaisePropertyChanged("telefono2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class personaContacto : persona {
        
        private string cargoField;
        
        private cliente clienteField;
        
        private int idPersonaContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersonaContacto {
            get {
                return this.idPersonaContactoField;
            }
            set {
                this.idPersonaContactoField = value;
                this.RaisePropertyChanged("idPersonaContacto");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLineaCredito", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLineaCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito;
        
        public insertarLineaCreditoRequest() {
        }
        
        public insertarLineaCreditoRequest(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            this.lineaCredito = lineaCredito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLineaCreditoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLineaCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarLineaCreditoResponse() {
        }
        
        public insertarLineaCreditoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarLineaCredito", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarLineaCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito;
        
        public actualizarLineaCreditoRequest() {
        }
        
        public actualizarLineaCreditoRequest(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            this.lineaCredito = lineaCredito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarLineaCreditoResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarLineaCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarLineaCreditoResponse() {
        }
        
        public actualizarLineaCreditoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarLineaCreditos", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarLineaCreditosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLineaCredito;
        
        public mostrarLineaCreditosRequest() {
        }
        
        public mostrarLineaCreditosRequest(int idLineaCredito) {
            this.idLineaCredito = idLineaCredito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostrarLineaCreditosResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class mostrarLineaCreditosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.LineaCreditoWS.lineaCredito @return;
        
        public mostrarLineaCreditosResponse() {
        }
        
        public mostrarLineaCreditosResponse(CrewmanSystem.LineaCreditoWS.lineaCredito @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LineaCreditoWSChannel : CrewmanSystem.LineaCreditoWS.LineaCreditoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LineaCreditoWSClient : System.ServiceModel.ClientBase<CrewmanSystem.LineaCreditoWS.LineaCreditoWS>, CrewmanSystem.LineaCreditoWS.LineaCreditoWS {
        
        public LineaCreditoWSClient() {
        }
        
        public LineaCreditoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LineaCreditoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineaCreditoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineaCreditoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse CrewmanSystem.LineaCreditoWS.LineaCreditoWS.insertarLineaCredito(CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest request) {
            return base.Channel.insertarLineaCredito(request);
        }
        
        public int insertarLineaCredito(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest inValue = new CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest();
            inValue.lineaCredito = lineaCredito;
            CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse retVal = ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).insertarLineaCredito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse> CrewmanSystem.LineaCreditoWS.LineaCreditoWS.insertarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest request) {
            return base.Channel.insertarLineaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.insertarLineaCreditoResponse> insertarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest inValue = new CrewmanSystem.LineaCreditoWS.insertarLineaCreditoRequest();
            inValue.lineaCredito = lineaCredito;
            return ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).insertarLineaCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse CrewmanSystem.LineaCreditoWS.LineaCreditoWS.actualizarLineaCredito(CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest request) {
            return base.Channel.actualizarLineaCredito(request);
        }
        
        public int actualizarLineaCredito(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest inValue = new CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest();
            inValue.lineaCredito = lineaCredito;
            CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse retVal = ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).actualizarLineaCredito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse> CrewmanSystem.LineaCreditoWS.LineaCreditoWS.actualizarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest request) {
            return base.Channel.actualizarLineaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoResponse> actualizarLineaCreditoAsync(CrewmanSystem.LineaCreditoWS.lineaCredito lineaCredito) {
            CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest inValue = new CrewmanSystem.LineaCreditoWS.actualizarLineaCreditoRequest();
            inValue.lineaCredito = lineaCredito;
            return ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).actualizarLineaCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse CrewmanSystem.LineaCreditoWS.LineaCreditoWS.mostrarLineaCreditos(CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest request) {
            return base.Channel.mostrarLineaCreditos(request);
        }
        
        public CrewmanSystem.LineaCreditoWS.lineaCredito mostrarLineaCreditos(int idLineaCredito) {
            CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest inValue = new CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest();
            inValue.idLineaCredito = idLineaCredito;
            CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse retVal = ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).mostrarLineaCreditos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse> CrewmanSystem.LineaCreditoWS.LineaCreditoWS.mostrarLineaCreditosAsync(CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest request) {
            return base.Channel.mostrarLineaCreditosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosResponse> mostrarLineaCreditosAsync(int idLineaCredito) {
            CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest inValue = new CrewmanSystem.LineaCreditoWS.mostrarLineaCreditosRequest();
            inValue.idLineaCredito = idLineaCredito;
            return ((CrewmanSystem.LineaCreditoWS.LineaCreditoWS)(this)).mostrarLineaCreditosAsync(inValue);
        }
    }
}
