//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.FamiliaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="FamiliaWS.FamiliaWS")]
    public interface FamiliaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/actualizarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/actualizarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.FamiliaWS.actualizarFamiliaResponse actualizarFamilia(CrewmanSystem.FamiliaWS.actualizarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/actualizarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/actualizarFamiliaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.actualizarFamiliaResponse> actualizarFamiliaAsync(CrewmanSystem.FamiliaWS.actualizarFamiliaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/eliminarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/eliminarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.FamiliaWS.eliminarFamiliaResponse eliminarFamilia(CrewmanSystem.FamiliaWS.eliminarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/eliminarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/eliminarFamiliaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.eliminarFamiliaResponse> eliminarFamiliaAsync(CrewmanSystem.FamiliaWS.eliminarFamiliaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/insertarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/insertarFamiliaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.FamiliaWS.insertarFamiliaResponse insertarFamilia(CrewmanSystem.FamiliaWS.insertarFamiliaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/insertarFamiliaRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/insertarFamiliaResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.insertarFamiliaResponse> insertarFamiliaAsync(CrewmanSystem.FamiliaWS.insertarFamiliaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/listarFamiliasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/listarFamiliasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.FamiliaWS.listarFamiliasResponse listarFamilias(CrewmanSystem.FamiliaWS.listarFamiliasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/listarFamiliasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/FamiliaWS/listarFamiliasResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.listarFamiliasResponse> listarFamiliasAsync(CrewmanSystem.FamiliaWS.listarFamiliasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/")]
    public partial class familia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idFamiliaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                this.idFamiliaField = value;
                this.RaisePropertyChanged("idFamilia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarFamilia", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.FamiliaWS.familia familia;
        
        public actualizarFamiliaRequest() {
        }
        
        public actualizarFamiliaRequest(CrewmanSystem.FamiliaWS.familia familia) {
            this.familia = familia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarFamiliaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarFamiliaResponse() {
        }
        
        public actualizarFamiliaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFamilia", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFamilia;
        
        public eliminarFamiliaRequest() {
        }
        
        public eliminarFamiliaRequest(int idFamilia) {
            this.idFamilia = idFamilia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarFamiliaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarFamiliaResponse() {
        }
        
        public eliminarFamiliaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFamilia", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFamiliaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.FamiliaWS.familia familia;
        
        public insertarFamiliaRequest() {
        }
        
        public insertarFamiliaRequest(CrewmanSystem.FamiliaWS.familia familia) {
            this.familia = familia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarFamiliaResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarFamiliaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarFamiliaResponse() {
        }
        
        public insertarFamiliaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFamilias", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFamiliasRequest {
        
        public listarFamiliasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarFamiliasResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarFamiliasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CrewmanSystem.FamiliaWS.familia[] @return;
        
        public listarFamiliasResponse() {
        }
        
        public listarFamiliasResponse(CrewmanSystem.FamiliaWS.familia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FamiliaWSChannel : CrewmanSystem.FamiliaWS.FamiliaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FamiliaWSClient : System.ServiceModel.ClientBase<CrewmanSystem.FamiliaWS.FamiliaWS>, CrewmanSystem.FamiliaWS.FamiliaWS {
        
        public FamiliaWSClient() {
        }
        
        public FamiliaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FamiliaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.FamiliaWS.actualizarFamiliaResponse CrewmanSystem.FamiliaWS.FamiliaWS.actualizarFamilia(CrewmanSystem.FamiliaWS.actualizarFamiliaRequest request) {
            return base.Channel.actualizarFamilia(request);
        }
        
        public int actualizarFamilia(CrewmanSystem.FamiliaWS.familia familia) {
            CrewmanSystem.FamiliaWS.actualizarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.actualizarFamiliaRequest();
            inValue.familia = familia;
            CrewmanSystem.FamiliaWS.actualizarFamiliaResponse retVal = ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).actualizarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.actualizarFamiliaResponse> CrewmanSystem.FamiliaWS.FamiliaWS.actualizarFamiliaAsync(CrewmanSystem.FamiliaWS.actualizarFamiliaRequest request) {
            return base.Channel.actualizarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.actualizarFamiliaResponse> actualizarFamiliaAsync(CrewmanSystem.FamiliaWS.familia familia) {
            CrewmanSystem.FamiliaWS.actualizarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.actualizarFamiliaRequest();
            inValue.familia = familia;
            return ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).actualizarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.FamiliaWS.eliminarFamiliaResponse CrewmanSystem.FamiliaWS.FamiliaWS.eliminarFamilia(CrewmanSystem.FamiliaWS.eliminarFamiliaRequest request) {
            return base.Channel.eliminarFamilia(request);
        }
        
        public int eliminarFamilia(int idFamilia) {
            CrewmanSystem.FamiliaWS.eliminarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.eliminarFamiliaRequest();
            inValue.idFamilia = idFamilia;
            CrewmanSystem.FamiliaWS.eliminarFamiliaResponse retVal = ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).eliminarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.eliminarFamiliaResponse> CrewmanSystem.FamiliaWS.FamiliaWS.eliminarFamiliaAsync(CrewmanSystem.FamiliaWS.eliminarFamiliaRequest request) {
            return base.Channel.eliminarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.eliminarFamiliaResponse> eliminarFamiliaAsync(int idFamilia) {
            CrewmanSystem.FamiliaWS.eliminarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.eliminarFamiliaRequest();
            inValue.idFamilia = idFamilia;
            return ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).eliminarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.FamiliaWS.insertarFamiliaResponse CrewmanSystem.FamiliaWS.FamiliaWS.insertarFamilia(CrewmanSystem.FamiliaWS.insertarFamiliaRequest request) {
            return base.Channel.insertarFamilia(request);
        }
        
        public int insertarFamilia(CrewmanSystem.FamiliaWS.familia familia) {
            CrewmanSystem.FamiliaWS.insertarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.insertarFamiliaRequest();
            inValue.familia = familia;
            CrewmanSystem.FamiliaWS.insertarFamiliaResponse retVal = ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).insertarFamilia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.insertarFamiliaResponse> CrewmanSystem.FamiliaWS.FamiliaWS.insertarFamiliaAsync(CrewmanSystem.FamiliaWS.insertarFamiliaRequest request) {
            return base.Channel.insertarFamiliaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.insertarFamiliaResponse> insertarFamiliaAsync(CrewmanSystem.FamiliaWS.familia familia) {
            CrewmanSystem.FamiliaWS.insertarFamiliaRequest inValue = new CrewmanSystem.FamiliaWS.insertarFamiliaRequest();
            inValue.familia = familia;
            return ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).insertarFamiliaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.FamiliaWS.listarFamiliasResponse CrewmanSystem.FamiliaWS.FamiliaWS.listarFamilias(CrewmanSystem.FamiliaWS.listarFamiliasRequest request) {
            return base.Channel.listarFamilias(request);
        }
        
        public CrewmanSystem.FamiliaWS.familia[] listarFamilias() {
            CrewmanSystem.FamiliaWS.listarFamiliasRequest inValue = new CrewmanSystem.FamiliaWS.listarFamiliasRequest();
            CrewmanSystem.FamiliaWS.listarFamiliasResponse retVal = ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).listarFamilias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.listarFamiliasResponse> CrewmanSystem.FamiliaWS.FamiliaWS.listarFamiliasAsync(CrewmanSystem.FamiliaWS.listarFamiliasRequest request) {
            return base.Channel.listarFamiliasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.FamiliaWS.listarFamiliasResponse> listarFamiliasAsync() {
            CrewmanSystem.FamiliaWS.listarFamiliasRequest inValue = new CrewmanSystem.FamiliaWS.listarFamiliasRequest();
            return ((CrewmanSystem.FamiliaWS.FamiliaWS)(this)).listarFamiliasAsync(inValue);
        }
    }
}
