//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrewmanSystem.ReporteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.CrewmanSystem.pucp.edu.pe/", ConfigurationName="ReporteWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoCliente del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosXCliente" +
            "Request", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosXCliente" +
            "Response")]
        CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse generarReportePedidosXCliente(CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosXCliente" +
            "Request", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosXCliente" +
            "Response")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse> generarReportePedidosXClienteAsync(CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.CrewmanSystem.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresEmpleado" +
            "sRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresEmpleado" +
            "sResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse generarReporteMejoresEmpleados(CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresEmpleado" +
            "sRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresEmpleado" +
            "sResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse> generarReporteMejoresEmpleadosAsync(CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePromocionReques" +
            "t", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePromocionRespon" +
            "se")]
        CrewmanSystem.ReporteWS.generarReportePromocionResponse generarReportePromocion(CrewmanSystem.ReporteWS.generarReportePromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePromocionReques" +
            "t", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePromocionRespon" +
            "se")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePromocionResponse> generarReportePromocionAsync(CrewmanSystem.ReporteWS.generarReportePromocionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.CrewmanSystem.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteQuejasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteQuejasResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ReporteWS.generarReporteQuejasResponse generarReporteQuejas(CrewmanSystem.ReporteWS.generarReporteQuejasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteQuejasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteQuejasResponse")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteQuejasResponse> generarReporteQuejasAsync(CrewmanSystem.ReporteWS.generarReporteQuejasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresClientes" +
            "Request", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresClientes" +
            "Response")]
        CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse generarReporteMejoresClientes(CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresClientes" +
            "Request", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteMejoresClientes" +
            "Response")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse> generarReporteMejoresClientesAsync(CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.CrewmanSystem.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosResponse" +
            "")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CrewmanSystem.ReporteWS.generarReportePedidosResponse generarReportePedidos(CrewmanSystem.ReporteWS.generarReportePedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReportePedidosResponse" +
            "")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosResponse> generarReportePedidosAsync(CrewmanSystem.ReporteWS.generarReportePedidosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteVisitasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteVisitasResponse" +
            "")]
        CrewmanSystem.ReporteWS.generarReporteVisitasResponse generarReporteVisitas(CrewmanSystem.ReporteWS.generarReporteVisitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteVisitasRequest", ReplyAction="http://services.CrewmanSystem.pucp.edu.pe/ReporteWS/generarReporteVisitasResponse" +
            "")]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteVisitasResponse> generarReporteVisitasAsync(CrewmanSystem.ReporteWS.generarReporteVisitasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReportePedidosXClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReportePedidosXCliente", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequestBody Body;
        
        public generarReportePedidosXClienteRequest() {
        }
        
        public generarReportePedidosXClienteRequest(CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReportePedidosXClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string estadoPedido;
        
        public generarReportePedidosXClienteRequestBody() {
        }
        
        public generarReportePedidosXClienteRequestBody(string tipoCliente, string estadoPedido) {
            this.tipoCliente = tipoCliente;
            this.estadoPedido = estadoPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReportePedidosXClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReportePedidosXClienteResponse", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponseBody Body;
        
        public generarReportePedidosXClienteResponse() {
        }
        
        public generarReportePedidosXClienteResponse(CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReportePedidosXClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReportePedidosXClienteResponseBody() {
        }
        
        public generarReportePedidosXClienteResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteMejoresEmpleados", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteMejoresEmpleadosRequest {
        
        public generarReporteMejoresEmpleadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteMejoresEmpleadosResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteMejoresEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteMejoresEmpleadosResponse() {
        }
        
        public generarReporteMejoresEmpleadosResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReportePromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReportePromocion", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReportePromocionRequestBody Body;
        
        public generarReportePromocionRequest() {
        }
        
        public generarReportePromocionRequest(CrewmanSystem.ReporteWS.generarReportePromocionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReportePromocionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idPromocion;
        
        public generarReportePromocionRequestBody() {
        }
        
        public generarReportePromocionRequestBody(string nombre, int idPromocion) {
            this.nombre = nombre;
            this.idPromocion = idPromocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReportePromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReportePromocionResponse", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReportePromocionResponseBody Body;
        
        public generarReportePromocionResponse() {
        }
        
        public generarReportePromocionResponse(CrewmanSystem.ReporteWS.generarReportePromocionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReportePromocionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReportePromocionResponseBody() {
        }
        
        public generarReportePromocionResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteQuejas", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteQuejasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idJefe;
        
        public generarReporteQuejasRequest() {
        }
        
        public generarReporteQuejasRequest(int idJefe) {
            this.idJefe = idJefe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteQuejasResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteQuejasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteQuejasResponse() {
        }
        
        public generarReporteQuejasResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteMejoresClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteMejoresClientes", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequestBody Body;
        
        public generarReporteMejoresClientesRequest() {
        }
        
        public generarReporteMejoresClientesRequest(CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteMejoresClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEmpleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        public generarReporteMejoresClientesRequestBody() {
        }
        
        public generarReporteMejoresClientesRequestBody(int idEmpleado, string nombre) {
            this.idEmpleado = idEmpleado;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteMejoresClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteMejoresClientesResponse", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponseBody Body;
        
        public generarReporteMejoresClientesResponse() {
        }
        
        public generarReporteMejoresClientesResponse(CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteMejoresClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReporteMejoresClientesResponseBody() {
        }
        
        public generarReporteMejoresClientesResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReportePedidos", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReportePedidosRequest {
        
        public generarReportePedidosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReportePedidosResponse", WrapperNamespace="http://services.CrewmanSystem.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReportePedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReportePedidosResponse() {
        }
        
        public generarReportePedidosResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteVisitasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteVisitas", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReporteVisitasRequestBody Body;
        
        public generarReporteVisitasRequest() {
        }
        
        public generarReporteVisitasRequest(CrewmanSystem.ReporteWS.generarReporteVisitasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteVisitasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idEmpleado;
        
        public generarReporteVisitasRequestBody() {
        }
        
        public generarReporteVisitasRequestBody(string nombre, int idEmpleado) {
            this.nombre = nombre;
            this.idEmpleado = idEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteVisitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteVisitasResponse", Namespace="http://services.CrewmanSystem.pucp.edu.pe/", Order=0)]
        public CrewmanSystem.ReporteWS.generarReporteVisitasResponseBody Body;
        
        public generarReporteVisitasResponse() {
        }
        
        public generarReporteVisitasResponse(CrewmanSystem.ReporteWS.generarReporteVisitasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteVisitasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReporteVisitasResponseBody() {
        }
        
        public generarReporteVisitasResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : CrewmanSystem.ReporteWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<CrewmanSystem.ReporteWS.ReporteWS>, CrewmanSystem.ReporteWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse CrewmanSystem.ReporteWS.ReporteWS.generarReportePedidosXCliente(CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest request) {
            return base.Channel.generarReportePedidosXCliente(request);
        }
        
        public byte[] generarReportePedidosXCliente(string tipoCliente, string estadoPedido) {
            CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest inValue = new CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequestBody();
            inValue.Body.tipoCliente = tipoCliente;
            inValue.Body.estadoPedido = estadoPedido;
            CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePedidosXCliente(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReportePedidosXClienteAsync(CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest request) {
            return base.Channel.generarReportePedidosXClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosXClienteResponse> generarReportePedidosXClienteAsync(string tipoCliente, string estadoPedido) {
            CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest inValue = new CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReportePedidosXClienteRequestBody();
            inValue.Body.tipoCliente = tipoCliente;
            inValue.Body.estadoPedido = estadoPedido;
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePedidosXClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse CrewmanSystem.ReporteWS.ReporteWS.generarReporteMejoresEmpleados(CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest request) {
            return base.Channel.generarReporteMejoresEmpleados(request);
        }
        
        public byte[] generarReporteMejoresEmpleados() {
            CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest inValue = new CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest();
            CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteMejoresEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReporteMejoresEmpleadosAsync(CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest request) {
            return base.Channel.generarReporteMejoresEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosResponse> generarReporteMejoresEmpleadosAsync() {
            CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest inValue = new CrewmanSystem.ReporteWS.generarReporteMejoresEmpleadosRequest();
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteMejoresEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReportePromocionResponse CrewmanSystem.ReporteWS.ReporteWS.generarReportePromocion(CrewmanSystem.ReporteWS.generarReportePromocionRequest request) {
            return base.Channel.generarReportePromocion(request);
        }
        
        public byte[] generarReportePromocion(string nombre, int idPromocion) {
            CrewmanSystem.ReporteWS.generarReportePromocionRequest inValue = new CrewmanSystem.ReporteWS.generarReportePromocionRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReportePromocionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.idPromocion = idPromocion;
            CrewmanSystem.ReporteWS.generarReportePromocionResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePromocion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePromocionResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReportePromocionAsync(CrewmanSystem.ReporteWS.generarReportePromocionRequest request) {
            return base.Channel.generarReportePromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePromocionResponse> generarReportePromocionAsync(string nombre, int idPromocion) {
            CrewmanSystem.ReporteWS.generarReportePromocionRequest inValue = new CrewmanSystem.ReporteWS.generarReportePromocionRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReportePromocionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.idPromocion = idPromocion;
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReporteQuejasResponse CrewmanSystem.ReporteWS.ReporteWS.generarReporteQuejas(CrewmanSystem.ReporteWS.generarReporteQuejasRequest request) {
            return base.Channel.generarReporteQuejas(request);
        }
        
        public byte[] generarReporteQuejas(int idJefe) {
            CrewmanSystem.ReporteWS.generarReporteQuejasRequest inValue = new CrewmanSystem.ReporteWS.generarReporteQuejasRequest();
            inValue.idJefe = idJefe;
            CrewmanSystem.ReporteWS.generarReporteQuejasResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteQuejas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteQuejasResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReporteQuejasAsync(CrewmanSystem.ReporteWS.generarReporteQuejasRequest request) {
            return base.Channel.generarReporteQuejasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteQuejasResponse> generarReporteQuejasAsync(int idJefe) {
            CrewmanSystem.ReporteWS.generarReporteQuejasRequest inValue = new CrewmanSystem.ReporteWS.generarReporteQuejasRequest();
            inValue.idJefe = idJefe;
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteQuejasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse CrewmanSystem.ReporteWS.ReporteWS.generarReporteMejoresClientes(CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest request) {
            return base.Channel.generarReporteMejoresClientes(request);
        }
        
        public byte[] generarReporteMejoresClientes(int idEmpleado, string nombre) {
            CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest inValue = new CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequestBody();
            inValue.Body.idEmpleado = idEmpleado;
            inValue.Body.nombre = nombre;
            CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteMejoresClientes(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReporteMejoresClientesAsync(CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest request) {
            return base.Channel.generarReporteMejoresClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteMejoresClientesResponse> generarReporteMejoresClientesAsync(int idEmpleado, string nombre) {
            CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest inValue = new CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReporteMejoresClientesRequestBody();
            inValue.Body.idEmpleado = idEmpleado;
            inValue.Body.nombre = nombre;
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteMejoresClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReportePedidosResponse CrewmanSystem.ReporteWS.ReporteWS.generarReportePedidos(CrewmanSystem.ReporteWS.generarReportePedidosRequest request) {
            return base.Channel.generarReportePedidos(request);
        }
        
        public byte[] generarReportePedidos() {
            CrewmanSystem.ReporteWS.generarReportePedidosRequest inValue = new CrewmanSystem.ReporteWS.generarReportePedidosRequest();
            CrewmanSystem.ReporteWS.generarReportePedidosResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePedidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReportePedidosAsync(CrewmanSystem.ReporteWS.generarReportePedidosRequest request) {
            return base.Channel.generarReportePedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReportePedidosResponse> generarReportePedidosAsync() {
            CrewmanSystem.ReporteWS.generarReportePedidosRequest inValue = new CrewmanSystem.ReporteWS.generarReportePedidosRequest();
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReportePedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CrewmanSystem.ReporteWS.generarReporteVisitasResponse CrewmanSystem.ReporteWS.ReporteWS.generarReporteVisitas(CrewmanSystem.ReporteWS.generarReporteVisitasRequest request) {
            return base.Channel.generarReporteVisitas(request);
        }
        
        public byte[] generarReporteVisitas(string nombre, int idEmpleado) {
            CrewmanSystem.ReporteWS.generarReporteVisitasRequest inValue = new CrewmanSystem.ReporteWS.generarReporteVisitasRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReporteVisitasRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.idEmpleado = idEmpleado;
            CrewmanSystem.ReporteWS.generarReporteVisitasResponse retVal = ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteVisitas(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteVisitasResponse> CrewmanSystem.ReporteWS.ReporteWS.generarReporteVisitasAsync(CrewmanSystem.ReporteWS.generarReporteVisitasRequest request) {
            return base.Channel.generarReporteVisitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CrewmanSystem.ReporteWS.generarReporteVisitasResponse> generarReporteVisitasAsync(string nombre, int idEmpleado) {
            CrewmanSystem.ReporteWS.generarReporteVisitasRequest inValue = new CrewmanSystem.ReporteWS.generarReporteVisitasRequest();
            inValue.Body = new CrewmanSystem.ReporteWS.generarReporteVisitasRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.idEmpleado = idEmpleado;
            return ((CrewmanSystem.ReporteWS.ReporteWS)(this)).generarReporteVisitasAsync(inValue);
        }
    }
}
